trainer:
  logger:
   class_path: lightning.pytorch.loggers.wandb.WandbLogger
   init_args:
     resume: allow
     name: "Classification DADA lr=1e-5 b32, new split, lyr decay 0.6, alpha=6, bin_width 1s"
     project: "vitin1k"
  devices: 1
  num_nodes: 1
  max_steps: 20000
  val_check_interval: 4000
  check_val_every_n_epoch: null
model:
  class_path: training.classification.Classification
  init_args:
    lr: 1e-5
    layerwise_lr_decay: 0.6
    lr_mode: "cosine_annealing"
    eta_min: 1e-8
    network:
      class_path: models.classification.vit_classification.VITClassification
data:
  class_path: datasets.dashcamaccident_datamodule.DashcamAccidentDataModule
  init_args:

    train_num_workers: 6  
    batch_size: 32
    val_batch_size: 32
    val_num_workers: 4 
    img_size: 224
    num_frames: 16
    window_stride: 1
    window_stride_val: 1
    sliding_window_fps: 10
    regression: False
    balancing: True