name: vmae
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - lightning
  - lightning-utilities
  - matplotlib
  - natsort
  - networkx
  - numpy
  - pandas
  - pillow
  - pytorch-lightning
  - scikit-learn
  - scipy
  - tokenizers
  - tqdm
  - transformers
  - opencv
  - pytorch==2.4.1
  - torchvision==0.19.1
  - pytorch-cuda==12.1
  - pip
  - pip:
      - Timm
      - Wandb
      - gitignore-parser